config/routes.rb
Rails.application.routes.draw do
  root 'apps#index'
  
  get '/login', to: 'login#index', as: 'login'
  get '/logout', to: 'login#log_out', as: 'logout'
  
  get '/apps', to: 'apps#index', as: 'apps'
  get '/apps/:app_name', to: 'apps#show', as: 'app'
  
  get '/apps/:app_name/:namespace_name', to: 'configuration#index', as: 'configurations'
  get '/apps/:app_name/:namespace_name/configurations/edit', to: 'configuration#edit', as: 'edit_configuration'

  get '/apps/:app_name/:namespace_name/histories', to: 'histories#index', as: 'histories'

  post '/login' => 'login#log_in'
  
  post '/apps/new' => 'apps#new'
  post '/apps/:app_name/new' => 'apps#add_namespace'
  
  post '/apps/:app_name/:namespace_name/configurations/' => 'configuration#commit_configurations'

  post '/apps/:app_name/:namespace_name/rollback' => 'configuration#rollback'
end

app/models/app.rb
class App
  attr_reader :name, :namespace, :version, :configurations

  def initialize(name, namespace,version)
    @name = name
    @namespace = namespace
    @version = version
    @configurations = Array.new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/config.rb
class Config
  attr_reader :key, :value
        
  def initialize(key, value)
    @key = key
    @value = value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  add_flash_types :danger, :info, :warning, :success 
  private
  def login
    unless cookies[:token]
      redirect_to login_path
    end
  end
  helper_method :login
end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  require 'httparty'
  require 'json'
  before_action :login
  def index
    response = HTTParty.get("http://localhost:8000/application", :headers => {"Authorization" => cookies[:token]})
    json_response = JSON.parse(response.body)
    @applications = Array.new
    for application in json_response do
        app = App.new(application["application_name"], application["namespace"][0], 0)
        @applications.push(app)
    end
  end

    
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
  require 'httparty'
  require 'json'
  before_action :login
  def index
    response = HTTParty.get("http://localhost:8000/applications", :headers => {"Authorization" => cookies[:token]})
    @applications = JSON.parse(response.body)
  end

  def show
    response = HTTParty.get("http://localhost:8000/applications/#{params[:app_name]}/namespaces", :headers => {"Authorization" => cookies[:token]})
    json_response = JSON.parse(response.body)
    @namespaces = json_response[0]["namespace"]
  end

  def new 
    headers = {"Authorization" => cookies[:token], "Content-Type"=> "application/json"}
    body = {:app_name => params[:app_name]}.to_json
    puts "app name = #{params[:app_name]}"
    url = "http://localhost:8000/applications"
    response = HTTParty.post(url , :headers =>  headers, :body => body)
    json = JSON.parse(response.body)
    redirect_to apps_path
  end

  def add_namespace
    headers = {"Authorization" => cookies[:token], "Content-Type"=> "application/json"}
    body = {:namespace_name => params[:namespace_name]}.to_json
    puts "namespace name = #{params[:namespace_name]}"
    url = "http://localhost:8000/applications/#{params[:app_name]}/namespaces"
    response = HTTParty.post(url , :headers =>  headers, :body => body)
    json = JSON.parse(response.body)
    redirect_to app_path(params[:app_name])
  end
  
end

app/controllers/configuration_controller.rb
class ConfigurationController < ApplicationController
  skip_before_action :verify_authenticity_token
  require 'httparty'
  require 'json'
  before_action :login

  def commit_configurations
    config_array = Array.new
    index_array = Array.new
    
    req_body = []

    params.each do |key, value|
      if !key["key-"].nil?
        index = key[4..-1]
        index_array.push(index)
      end
    end

    for index in index_array do
      config = Config.new(params["key-" + index], params["value-" + index])
      config_array.push(config)
    end

    config_array.each do |config|
      req_body.push({"key": config.key,"value": config.value})
    end
    response = HTTParty.post("http://localhost:8000/applications/#{params[:app_name]}/namespaces/#{params[:namespace_name]}/configurations",
      :body => req_body.to_json,
      :headers => { 'Content-Type' => 'application/json' , "Authorization" => cookies['token']})

    json_response = JSON.parse(response.body)
    if (json_response["status"] == 201)
      redirect_to configurations_path(params[:app_name],params[:namespace_name])
    else
      redirect_to apps_path, danger:"Add new configuration fail"
    end
  end
  
  def index
    url = "http://localhost:8000/applications/#{params[:app_name]}/namespaces/#{params[:namespace_name]}/configurations/latest"
    headers = {"Authorization" => cookies['token']}
    response = HTTParty.get(url, :headers => headers)
    response_body = JSON.parse(response.body)
    @configurations = response_body['configurations']
    @active_version = response_body['version']
  end

  def edit
    url = "http://localhost:8000/applications/#{params[:app_name]}/namespaces/#{params[:namespace_name]}/configurations/latest"
    headers = {"Authorization" => cookies['token']}
    response = HTTParty.get(url, :headers => headers)
    response_body = JSON.parse(response.body)
    @configurations = response_body['configurations']
    @active_version = response_body['version']
  end

  def rollback
    url = "http://localhost:8000/applications/#{params[:app_name]}/namespaces/#{params[:namespace_name]}/configurations/rollback"
    headers = {"Authorization" => cookies['token']}
    body = {
            "version" => params['version'].to_i
            }
    response = HTTParty.post(url, :headers => headers, :body => body.to_json)
    json_response = JSON.parse(response.body)
    if (json_response["status"] == 200)
      redirect_to configurations_path(params[:app_name],params[:namespace_name])
    else
      redirect_to apps_path, danger:"Rollback Failed"
    end
  end

end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  require 'httparty'
  require 'json'
  before_action :login
  def index
    response = HTTParty.get("http://localhost:8000/application", :headers => {"Authorization" => cookies[:token]})
    json_response = JSON.parse(response.body)
    @applications = Array.new
    for application in json_response do
        app = App.new(application["application_name"], application["namespace"][0], 0)
        @applications.push(app)
    end
  end

    
end

app/controllers/histories_controller.rb
class HistoriesController < ApplicationController
  skip_before_action :verify_authenticity_token
  require 'httparty'
  require 'json'
  before_action :login

  def index
    headers = {"Authorization" => cookies['token']}
    url = "http://localhost:8000/applications/#{params[:app_name]}/namespaces/#{params[:namespace_name]}/histories"
    response = HTTParty.get(url, :headers => headers)
    @histories = JSON.parse(response.body)
  end

end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :verify_authenticity_token

  require 'httparty'
  require 'json'

  def index
    puts "Hiiiii"
  end

  def log_in
    @response = HTTParty.post('http://localhost:8000/login',
      :headers => {'Content-Type'=>'application/json'},
      :body => {:username => params['username'], :password => params['password']}.to_json)
      json = JSON.parse(@response.body)
      if (json["status"] == 200)
        cookies[:token] = { :value => json["token"], :expires => Time.now + 3600}
        redirect_to apps_path
      else
        #flash[:error] = 'Invalid Username or Password'
        redirect_to login_path, danger:"Invalid Username or Password"
      end

      puts json['token'].to_s
  end

  def log_out
    puts "Hello"
    @response = HTTParty.get('http://localhost:8000/ping')
    json = JSON.parse(@response.body)
    if (json["success"] == "pong")
      cookies.delete(:token)
      redirect_to login_path
    else
      redirect_to application_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/configuration_helper.rb
module ConfigurationHelper
end

app/helpers/histories_helper.rb
module HistoriesHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/views/apps/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row">
  <div class="col-10">
    <%= render 'layouts/path'%>
  </div>
  <div class="col-2">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    New App
  </button>
  </div>
</div>
<hr>
<% unless @applications.nil? %>
  <% @applications.each do |app| %>
    <%= link_to app_path(app['application_name']) do%>
      <div class="row">
        <div class="col-12  apps-list-item list-group-item-action">
            <span><%= app['application_name']%></span>
        </div>
      </div>
    <% end %>
  <% end %>
<% else %>
  <p>You don't have any app, let's create your first app!</p>
<% end %>


<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag app_path("new"), method: :post do %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create New App</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body row">
        <div class="offset-1 col-4">
        <%= label_tag 'App name' %>
        </div>
        <div class="col-7 d-flex">
        <%= text_field_tag "app_name" , nil , size: 30%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= submit_tag "Create app" , class: "btn btn-primary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/apps/show.html.erb
<%= render 'layouts/navbar'%>
<div class="row">
  <div class="col-10">
    <%= render 'layouts/path'%>
  </div>
  <div class="col-2">
  <!-- Button trigger modal -->
  <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
    New Namespace
  </button>
  </div>
</div>
<hr>
<% unless @namespaces.nil?%>
<% @namespaces.each do |namespace| %>
  <%= link_to configurations_path(params[:app_name], namespace) do%>
    <div class="row">
      <div class="col-12  apps-list-item list-group-item-action">
          <span><%= namespace%></span>
      </div>
    </div>
  <% end %>
<% end %>
<%else%>
 <%=render html: "you don't have any namespace, let's create your first namespace"%> 
<% end %>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <%= form_tag app_path("#{params[:app_name]}")+"/new", method: :post do %>
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Create New App</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body row">
        <div class="offset-1 col-4">
        <%= label_tag 'Namespace name' %>
        </div>
        <div class="col-7 d-flex">
        <%= text_field_tag "namespace_name" , nil , size: 30%>
        </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
        <%= submit_tag "Create namespace" , class: "btn btn-primary"%>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/configuration/edit.html.erb
<script>
  var tr_idx = 7
</script>
<%= render 'layouts/navbar'%>
<div class="row">
  <div class="col-12">
    <%= render 'layouts/path'%>
  </div>
</div>
<hr>

<table class="app-info">
  <tr>
    <td>Application</td>
    <td><%= params[:app_name] %></td>
  </tr>
    <td>Namespace</td>
    <td><%= params[:namespace_name] %></td>
  <tr>
    <td>Version </td>
    <td><%= @active_version %></td>
  </tr>
</table>


<form method="post" action=".">
  <input type="hidden" name="app" value="<%= params[:app_name] %>">
  <input type="hidden" name="namespace" value="<%= params[:namespace_name] %>">
  <table class="edit-configs" id="edit-configs">
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
    <% unless @configurations.nil?%>
    <% @configurations.each_with_index do |config, index| %>
      <tr id="field-<%= index %>">
        <td><input type="text" name="key-<%= index %>" value="<%= config['key'] %>"></td>
        <td><input type="text" name="value-<%= index %>" value="<%= config['value'] %>"></td>
        <td class="del-span"><button type="button" id="btn-field-<%= index %>" class="btn btn-danger del-btn"><i class="glyphicon glyphicon-trash"></i></button></td>
      </tr>
    <% end %>
    <% end %>
  </table>
  <div class="row">
    <div class="col-md-5">
    </div>
    <div class="col-md-2">
      <button type="button" class="btn btn-primary add-cfg-btn"><i class="glyphicon glyphicon-plus"></i>&nbsp;Add</button>
    </div>
  </div>
  <div class="row">
    <div class="col-md-1">
      <input type="submit" class="btn btn-success" value="Commit">
    </div>
    <div class="col-2">
      <%= link_to "Cancel", configurations_path(params[:app_name],params[:namespace_name]), class: "btn btn-danger" %>
    </div>
  </div>
</form>

app/views/configuration/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row">
  <div class="col-10">
    <%= render 'layouts/path'%>
  </div>
  <div class="col-2">
    <%= link_to "Edit Config",edit_configuration_path(params[:app_name],params[:namespace_name]), class: "btn btn-primary" %>
  </div>
</div>
<hr>

<%= render 'layouts/config_menu'%>
<table class="app-info">
  <tr>
    <td>Application</td>
    <td><%= params[:app_name] %></td>
  </tr>
    <td>Namespace</td>
    <td><%= params[:namespace_name] %></td>
  <tr>
    <td>Version </td>
    <td><%= @active_version %></td>
  </tr>
</table>

<% unless @configurations.nil?%>
  <table class="configs">
    <tr>
      <th>Key</th>
      <th>Value</th>
    </tr>
    <% @configurations.each do |config| %>
      <tr>
        <td><%= config['key'] %></td>
        <td><%= config['value'] %></td>
      </tr>
    <% end %>
  </table>
  <% else %>
  <h4 class="text-center text-danger">You don't have any config. Let's create one</h4>
<% end %>

app/views/dashboard/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row">
  <div class="col-10">
    <h1 class="text-center">Dashboard</h1>
  </div>
</div>
<hr>
    
<% @applications.each do |app| %>
  <div class="row">
    <div class="col-12">
      <%= button_to("#{app.name}", configuration_path ,params: {namespace: app.namespace, app: app.name}, method: :get, class: "btn btn-default btn-block") %>
    </div>
  </div>
<% end %>

app/views/histories/index.html.erb
<%= render 'layouts/navbar'%>
<div class="row">
  <div class="col-10">
    <%= render 'layouts/path'%>
  </div>
</div>
<hr>
<%= render 'layouts/config_menu'%>
<% unless @histories.nil? %>
  <% @histories.each do |history|%>

  <div class="flex flex-column lh-copy">
    <div class="f5">
      <span class="b"><%= history['username']%></span>
    </div>

    <div class="f5 gray">
      <time id="ember1630" title="2018-07-19 03:53:34 UTC" datetime="2018-07-19T03:53:34Z" class="timeago ember-view"><%= history['created_at']%>
  </time>
        from v<%= history['predecessor_version']%>
        to v<%= history['successor_version']%>
    </div>
    <%= history['created']%>
    <%= history['changed']%>
    <%= history['deleted']%>
    <%= form_tag 'rollback' do  %>
      <%= hidden_field_tag 'version', history['successor_version'] %>
      <%= submit_tag "rollback" , class: "btn btn-primary"%>
    <% end %>
  </div>
  <% end %>
  <% else %>
  <h3>You don't have any history</h3>
<% end %>

app/views/layouts/_config_menu.html.erb
<div class="row">
  <div class="col-2 active">
    <%= link_to "Configurations", configurations_path%>
  </div>
  <div class="col-2">
    <%= link_to "History", histories_path%>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="row">
  <div class="col-12">
    <nav class="navbar navbar-expand-lg navbar-light bg-light col-12">
      <a class="navbar-brand col-3" href=<%=apps_path%>>Comet</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse col-2 offset-7" id="navbarSupportedContent">
        <%= button_to("Log Out", "/logout", method: :get, class: "btn btn-default logout-btn") %>
      </div>
    </nav>
  </div>
</div>

app/views/layouts/_path.html.erb
<h3>
  <%= link_to content_tag(:span, "Applications"), apps_path%>
  <% if params[:app_name]!=nil %>
    <i class="arrow right"></i>
  <% end %>
  <% if params[:namespace_name]!=nil %>
    <%= link_to content_tag(:span, "#{params[:app_name]}"), app_path(params[:app_name])%>
    <i class="arrow right"></i>
    <%=  content_tag(:span, "#{params[:namespace_name]}") %>
  <% else%>
    <%= content_tag(:span, "#{params[:app_name]}") %>
  <% end %>
</h3>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CometUi</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">

    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body>
    <div class="container">
    <div class='row'>
      <% flash.each do |name, msg| %>
        <div class='alert alert-<%= name %>'>
          <%= msg %>
        </div>
      <%end%>
    </div>
    <%= yield %>
    </div>
  </body>
</html>

app/views/login/index.html.erb
<div class="row">
  <div class="col-12 jumbotron text-center" style="background-color: transparent !important;">
        <h1>COMET UI</h1> 
  </div>
</div>
<div class="row">
  <div class="col-md-12">
    <div class="modal-dialog" style="margin-bottom:0">
      <div class="panel-default modal-content">
        <div class="panel-heading">
            <h3 class="panel-title">Sign In</h3>
        </div>
        <div class="panel-body">
          <form role="form" method="POST" action="/login">
            <fieldset>
              <div class="form-group">
                  <input class="form-control" placeholder="Username" name="username" type="text" autofocus="" required>
              </div>
              <div class="form-group">
                  <input class="form-control" placeholder="Password" name="password" type="password" value="" required>
              </div>
              <div class="checkbox">
                  <label>
                      <input name="remember" type="checkbox" value="Remember Me">Remember Me
                  </label>
              </div>
              <div class="form-group">
                <div align="center">
                  <button type="submit" class="btn btn-default btn-block btn-sm btn-success" value="login">Login</button>
                </div>
              </div>
            </fieldset>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>